[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true

[[redirects]]
  from = "/rest/*"
  to = "/.netlify/functions/rest"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
